version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: sorriso_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sorrisodb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./Back-End
    container_name: sorriso_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      PORT: 3000
      JWT_SECRET: segredo
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: sorrisodb
    volumes:
      - ./Back-End:/app
      - /app/node_modules
      - ./Back-End/uploads:/app/uploads

  frontend:
    build:
      context: ./Front-End
    container_name: sorriso_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./Front-End:/app
      - /app/node_modules

volumes:
  mysql_data: